function init_ga_spider()
    global GA_PARAMS;
    % parameters
    GA_PARAMS = struct( ...
        'POPULATION_SIZE', 100, ...
        'GENERATIONS', 100, ...
        'SPIDER_INPUT_SIZE', 24, ...
        'SPIDER_OUTPUT_SIZE', 24, ...
        'NUM_OF_SURVIVORS', 20, ...
        'TOP_SURVIVORS', 16, ...
        'RANDOM_SPIDERS', 4, ...
        'MUTATION_RATE', 0.002, ...
        'MAX_MUTATION_ANGLE', 1, ...
        'TRAINING_FRAMES', 300, ...
        'GAIT_FRAMES', 300, ...
        'MIN_ANGLE', -pi/2, ...
        'MAX_ANGLE',  pi/2, ...
        'MAX_ANGLE_DELTA', 2, ...
        'MIN_FOOT_HEIGHT', -2.0, ...
        'STANCE_Z_TARGET', -1, ...
        'Z_BAND_TOL', 0.05, ...
        'MAX_LIFT_ALLOWED', 0.15, ...
        'STANCE_MOTION_THRESHOLD', 0.02, ...
        'OVERLAPPING_LEGS_FITNESS_SCALAR', -0.1, ...
        'FEET_THROUGH_FLOOR_SCALAR', -0.1, ...
        'ANGLE_CHANGE_SCALAR', -0.01, ...
        'MOVEMENT_SCALAR', 2.0, ...
        'MIN_MOVING_JOINTS_FOR_REWARD', 4, ...
        'MOVEMENT_EPSILON', 0.01, ...
        'LOW_MOVEMENT_PENALTY_SCALAR', -4.0, ...
        'MIN_MOVING_JOINTS_THRESHOLD', 3, ...
        'BAND_REWARD_SCALAR', 0.8, ...
        'PENETRATION_SCALAR', -2.0, ...
        'EXCESS_LIFT_SCALAR', -0.2, ...
        'VARIANCE_SCALAR', -0.5, ...
        'BOUNDARY_MARGIN', 0.2, ...
        'BOUNDARY_PENALTY_SCALAR', -0.5 ...
    );

    population = generate_population(GA_PARAMS.POPULATION_SIZE, GA_PARAMS.SPIDER_INPUT_SIZE, GA_PARAMS.SPIDER_OUTPUT_SIZE);

    % Preallocate history of best fitness per generation
    best_fitness_history = zeros(1, GA_PARAMS.GENERATIONS);

    for i=1:GA_PARAMS.GENERATIONS
        disp("Generation: " + i);
        gaits = generate_gaits(population, GA_PARAMS.TRAINING_FRAMES);

        fitness_values = evaluate_fitness(gaits);

        % Store best fitness this generation
        best_fitness_history(i) = max(fitness_values);

        parents = get_parents(population, fitness_values, GA_PARAMS.NUM_OF_SURVIVORS, GA_PARAMS.TOP_SURVIVORS, GA_PARAMS.RANDOM_SPIDERS, GA_PARAMS.SPIDER_INPUT_SIZE, GA_PARAMS.SPIDER_OUTPUT_SIZE);

        population = generate_offspring(parents);
    end

    % Plot best fitness per generation
    ga_graph_fig = figure;
    plot(1:GA_PARAMS.GENERATIONS, best_fitness_history, '-r', 'LineWidth', 2);
    xlabel('Generation');
    ylabel('Best Fitness');
    title('GA Best Fitness per Generation');
    grid on;

    final_gaits = generate_gaits(population, GA_PARAMS.GAIT_FRAMES);

    final_fitness_values = evaluate_fitness(final_gaits);

    best_gait = cell2mat(get_best_gait(final_gaits, final_fitness_values)');

    best_spider = get_best_spider(population, final_fitness_values);

    % Create a new figure for the spider animation to avoid overwriting the graph
    figure; 
    % Optional: save video of best gait
    save_spider_gait_video(best_gait, 'best_spider_gait.mp4', 10, ga_graph_fig);    % Optional: visualize best gait
    % spider_gait(best_gait);

    % Save best gait to .mat file for use by the NN for training

    save('bestGait.mat', 'best_gait');   
end
    
